/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/AWTForms/Dialog.java to edit this template
 */
package org.example.view;

import java.awt.Dimension;
import org.example.backend.interprete.error.Errores;

import javax.swing.table.DefaultTableModel;
import java.util.LinkedList;

import org.example.backend.interprete.simbol.Simbolo;

/**
 * @author giovanic
 */
public class ReporteD extends java.awt.Dialog {

    private DefaultTableModel modelo;

    /**
     * Creates new form ReporteD
     */
    public ReporteD(java.awt.Frame parent) {
        super(parent, true);
        initComponents();
        setMinimumSize(new Dimension(500, 80));
        setPreferredSize(new Dimension(500, 80));
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();

        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowClosing(java.awt.event.WindowEvent evt) {
                closeDialog(evt);
            }
        });

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jTable1.setMinimumSize(new java.awt.Dimension(500, 80));
        jTable1.setPreferredSize(new java.awt.Dimension(500, 80));
        jScrollPane1.setViewportView(jTable1);

        add(jScrollPane1, java.awt.BorderLayout.CENTER);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * Closes the dialog
     */
    private void closeDialog(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_closeDialog
        setVisible(false);
        dispose();
    }//GEN-LAST:event_closeDialog

    public void loadTable(LinkedList<Errores> err, String[] nombreCol) {
        //TipoError tipo, String desc, int lineaa, int columa
        modelo = new DefaultTableModel();
        modelo.setColumnIdentifiers(nombreCol);

        while (modelo.getRowCount() > 0) {
            modelo.removeRow(0);
        }

        for (Errores errores : err) {
            Object[] tmp = new Object[4];
            tmp[0] = errores.getTipo();
            tmp[1] = errores.getdescripcion();
            tmp[2] = errores.getlinea();
            tmp[3] = errores.getcoluma();
            modelo.addRow(tmp);
        }
        jTable1.setModel(modelo);
        jTable1.getColumnModel().getColumn(0).setPreferredWidth(100);
        jTable1.getColumnModel().getColumn(1).setPreferredWidth(250);
        jTable1.getColumnModel().getColumn(2).setPreferredWidth(75);
        jTable1.getColumnModel().getColumn(3).setPreferredWidth(75);
    }

    public void loadTable2(LinkedList<Simbolo> sym, String[] nombreCol) {
        //TipoError tipo, String desc, int lineaa, int columa
        modelo = new DefaultTableModel();
        modelo.setColumnIdentifiers(nombreCol);

        while (modelo.getRowCount() > 0) {
            modelo.removeRow(0);
        }

        for (Simbolo s : sym) {
            Object[] tmp = new Object[4];
            tmp[0] = s.getTipo().getTipo();
            tmp[1] = s.getId();
            tmp[2] = s.getValue();
            tmp[3] = s.isEsConstante();
            modelo.addRow(tmp);
        }
        jTable1.setModel(modelo);
        jTable1.getColumnModel().getColumn(0).setPreferredWidth(80);
        jTable1.getColumnModel().getColumn(1).setPreferredWidth(100);
        jTable1.getColumnModel().getColumn(2).setPreferredWidth(265);
        jTable1.getColumnModel().getColumn(3).setPreferredWidth(90);
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTable1;
    // End of variables declaration//GEN-END:variables
}
