package org.example.view;

import java.awt.Image;
import java.awt.event.MouseEvent;
import java.awt.event.MouseListener;
import java.io.File;
import java.io.StringReader;
import java.util.LinkedList;
import java.util.Objects;
import javax.swing.ImageIcon;
import javax.swing.JOptionPane;
import javax.swing.Box;
import javax.swing.JMenu;
import javax.swing.JTextArea;
import org.example.backend.interprete.abstracto.Instruccion;
import org.example.backend.interprete.analisis.Parser;
import org.example.backend.interprete.analisis.Scan;
import org.example.backend.interprete.simbol.TablaSimbolo;
import org.example.backend.interprete.simbol.Tree;

import org.example.backend.util.FilesControl;
import org.example.backend.util.GestionTab;

/**
 * @author giovanic
 */
public class VentanaPrincipal extends javax.swing.JFrame {

    private final FilesControl control;
    private final GestionTab gestionTab;

    /**
     * Creates new form VentanaPrincipal
     */
    public VentanaPrincipal() {
        initComponents();
        barraMenu.add(Box.createHorizontalGlue());
        build = new JMenu("Build");
        barraMenu.add(build);
        barraMenu.revalidate();

        this.control = new FilesControl();
        this.gestionTab = new GestionTab(tab, control);

        Image icon = new ImageIcon(getClass().getResource("/logoTransparente.png")).getImage();
        setIconImage(icon);

        loadActionBuild();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        tab = new javax.swing.JTabbedPane();
        jScrollPane1 = new javax.swing.JScrollPane();
        salidaTxtArea = new javax.swing.JTextArea();
        barraMenu = new javax.swing.JMenuBar();
        menuArchivo = new javax.swing.JMenu();
        nuevoMenuItem = new javax.swing.JMenuItem();
        abrirMenuItem = new javax.swing.JMenuItem();
        guardarMenuItem = new javax.swing.JMenuItem();
        eliminarTabMenuItem = new javax.swing.JMenuItem();
        menuReport = new javax.swing.JMenu();
        verReporteItemMenu = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("JavaCraft");
        setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        setMinimumSize(new java.awt.Dimension(1082, 658));

        salidaTxtArea.setColumns(20);
        salidaTxtArea.setRows(5);
        jScrollPane1.setViewportView(salidaTxtArea);

        menuArchivo.setText("Accion");

        nuevoMenuItem.setText("Nuevo Archivo");
        nuevoMenuItem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                nuevoMenuItemActionPerformed(evt);
            }
        });
        menuArchivo.add(nuevoMenuItem);

        abrirMenuItem.setText("Abrir Archivo");
        abrirMenuItem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                abrirMenuItemActionPerformed(evt);
            }
        });
        menuArchivo.add(abrirMenuItem);

        guardarMenuItem.setText("Guardar Archivo");
        guardarMenuItem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                guardarMenuItemActionPerformed(evt);
            }
        });
        menuArchivo.add(guardarMenuItem);

        eliminarTabMenuItem.setText("Eliminar Pestaña");
        eliminarTabMenuItem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                eliminarTabMenuItemActionPerformed(evt);
            }
        });
        menuArchivo.add(eliminarTabMenuItem);

        barraMenu.add(menuArchivo);

        menuReport.setText("Reportes");

        verReporteItemMenu.setText("Ver Reportes");
        verReporteItemMenu.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                verReporteItemMenuActionPerformed(evt);
            }
        });
        menuReport.add(verReporteItemMenu);

        barraMenu.add(menuReport);

        setJMenuBar(barraMenu);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 1070, Short.MAX_VALUE)
                    .addComponent(tab)))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(tab, javax.swing.GroupLayout.DEFAULT_SIZE, 400, Short.MAX_VALUE)
                .addGap(18, 18, 18)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 202, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void nuevoMenuItemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_nuevoMenuItemActionPerformed
        File archivo = control.crearArchivo();
        if (!Objects.isNull(archivo)) {
            String contenido = control.getContenido(archivo.getAbsolutePath());
            gestionTab.addTab(archivo, contenido);
        }
    }//GEN-LAST:event_nuevoMenuItemActionPerformed

    private void abrirMenuItemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_abrirMenuItemActionPerformed
        File archivo = control.getFile();
        if (!Objects.isNull(archivo)) {
            String contenido = control.getContenido(archivo.getAbsolutePath());
            gestionTab.addTab(archivo, contenido);
        }
    }//GEN-LAST:event_abrirMenuItemActionPerformed

    private void guardarMenuItemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_guardarMenuItemActionPerformed
        if (tab.getSelectedIndex() != -1) {
            gestionTab.sobreEscribir(tab.getSelectedIndex());
        }
    }//GEN-LAST:event_guardarMenuItemActionPerformed

    private void eliminarTabMenuItemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_eliminarTabMenuItemActionPerformed
        if (tab.getSelectedIndex() != -1) {
            gestionTab.deleteTab(tab.getSelectedIndex());
        } else {
            JOptionPane.showMessageDialog(null, "No hay pesañas que cerrar", "Error", JOptionPane.ERROR_MESSAGE);
        }
    }//GEN-LAST:event_eliminarTabMenuItemActionPerformed

    private void verReporteItemMenuActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_verReporteItemMenuActionPerformed
        ReporteD rd = new ReporteD(this);
        rd.setLocationRelativeTo(null);
        rd.setVisible(true);
    }//GEN-LAST:event_verReporteItemMenuActionPerformed

    private void loadActionBuild() {
        build.addMouseListener(new MouseListener() {
            @Override
            public void mouseClicked(MouseEvent e) {
                if (tab.getSelectedIndex() != -1) {
                    int index = tab.getSelectedIndex();
                    Tab temp = (Tab) tab.getComponentAt(index);
                    String texto = temp.getVistaContenido() + "\n";
                    try {
                        StringReader stringReader = new StringReader(texto);
                        Parser parser = new Parser(new Scan(stringReader));
                        var resultado = parser.parse();
                        var ast = new Tree((LinkedList<Instruccion>) resultado.value);
                        var tabla = new TablaSimbolo();
                        tabla.setNombre("GLOBAL");
                        ast.setConsola("");
                        for (var a : ast.getInstrucciones()) {
                            var res = a.interpretar(ast, tabla);
                        }
                        System.out.println(ast.getConsola());
                    } catch (Exception ex) {
                        System.out.println("Algo salio mal");
                        //noinspection ThrowablePrintedToSystemOut
                        System.out.println(ex);

                    }
                }
            }

            @Override
            public void mousePressed(MouseEvent e) {
            }

            @Override
            public void mouseReleased(MouseEvent e) {
            }

            @Override
            public void mouseEntered(MouseEvent e) {
            }

            @Override
            public void mouseExited(MouseEvent e) {
            }
        });

    }

    private javax.swing.JMenu build;
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JMenuItem abrirMenuItem;
    private javax.swing.JMenuBar barraMenu;
    private javax.swing.JMenuItem eliminarTabMenuItem;
    private javax.swing.JMenuItem guardarMenuItem;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JMenu menuArchivo;
    private javax.swing.JMenu menuReport;
    private javax.swing.JMenuItem nuevoMenuItem;
    private javax.swing.JTextArea salidaTxtArea;
    private javax.swing.JTabbedPane tab;
    private javax.swing.JMenuItem verReporteItemMenu;
    // End of variables declaration//GEN-END:variables
}
