package org.example.view;

import java.io.File;
import java.util.Objects;
import javax.swing.JOptionPane;
import org.example.backend.FilesControl;
import org.example.backend.GestionArchivos;

/**
 *
 * @author giovanic
 */
public class VentanaPrincipal extends javax.swing.JFrame {

    private final FilesControl control;
    private final GestionArchivos gestionArchivos;
    private final GestionTab gestionTab;

    /**
     * Creates new form VentanaPrincipal
     */
    public VentanaPrincipal() {
        initComponents();
        this.control = new FilesControl();
        this.gestionArchivos = new GestionArchivos();
        this.gestionTab = new GestionTab(tab);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        tab = new javax.swing.JTabbedPane();
        jScrollPane1 = new javax.swing.JScrollPane();
        salidaTxtArea = new javax.swing.JTextArea();
        jMenuBar1 = new javax.swing.JMenuBar();
        menuArchivo = new javax.swing.JMenu();
        nuevoMenuItem = new javax.swing.JMenuItem();
        abrirMenuItem = new javax.swing.JMenuItem();
        guardarMenuItem = new javax.swing.JMenuItem();
        eliminarTabMenuItem = new javax.swing.JMenuItem();
        jMenu2 = new javax.swing.JMenu();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("JavaCraft");
        setMinimumSize(new java.awt.Dimension(1082, 658));

        salidaTxtArea.setColumns(20);
        salidaTxtArea.setRows(5);
        jScrollPane1.setViewportView(salidaTxtArea);

        menuArchivo.setText("Archivo");

        nuevoMenuItem.setText("Nuevo Archivo");
        nuevoMenuItem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                nuevoMenuItemActionPerformed(evt);
            }
        });
        menuArchivo.add(nuevoMenuItem);

        abrirMenuItem.setText("Abrir Archivo");
        abrirMenuItem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                abrirMenuItemActionPerformed(evt);
            }
        });
        menuArchivo.add(abrirMenuItem);

        guardarMenuItem.setText("Guardar Archivo");
        guardarMenuItem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                guardarMenuItemActionPerformed(evt);
            }
        });
        menuArchivo.add(guardarMenuItem);

        eliminarTabMenuItem.setText("Eliminar Pestaña");
        eliminarTabMenuItem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                eliminarTabMenuItemActionPerformed(evt);
            }
        });
        menuArchivo.add(eliminarTabMenuItem);

        jMenuBar1.add(menuArchivo);

        jMenu2.setText("Edit");
        jMenuBar1.add(jMenu2);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jScrollPane1)
                    .addComponent(tab))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(tab)
                .addGap(18, 18, 18)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 202, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void nuevoMenuItemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_nuevoMenuItemActionPerformed
        String nombre = JOptionPane.showInputDialog(null, "Ingrese el nombre del archivo", "Nuevo", JOptionPane.PLAIN_MESSAGE);
        if (nombre != null && !nombre.isEmpty()) {
            JOptionPane.showMessageDialog(null, nombre);
        } else {
            System.out.println("err -> " + nombre);
        }
    }//GEN-LAST:event_nuevoMenuItemActionPerformed

    private void abrirMenuItemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_abrirMenuItemActionPerformed
        File archivo = control.getFile();
        if (!Objects.isNull(archivo)) {
            System.out.println(" -> " + archivo.getAbsolutePath());
            String contenido = control.getContenido(archivo.getAbsolutePath());
            gestionTab.addTab(archivo.getName(), contenido);
            //gestionArchivos.addFile(archivo);
        }
    }//GEN-LAST:event_abrirMenuItemActionPerformed

    private void guardarMenuItemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_guardarMenuItemActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_guardarMenuItemActionPerformed

    private void eliminarTabMenuItemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_eliminarTabMenuItemActionPerformed
        //gestionArchivos.removeFile(gestionArchivos.search(new File("olls")));
        if (tab.getSelectedIndex() != -1) {
            tab.removeTabAt(tab.getSelectedIndex());
        } else {
            JOptionPane.showMessageDialog(null, "No hay pesañas que cerrar", "Error", JOptionPane.ERROR_MESSAGE);
        }
    }//GEN-LAST:event_eliminarTabMenuItemActionPerformed

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JMenuItem abrirMenuItem;
    private javax.swing.JMenuItem eliminarTabMenuItem;
    private javax.swing.JMenuItem guardarMenuItem;
    private javax.swing.JMenu jMenu2;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JMenu menuArchivo;
    private javax.swing.JMenuItem nuevoMenuItem;
    private javax.swing.JTextArea salidaTxtArea;
    private javax.swing.JTabbedPane tab;
    // End of variables declaration//GEN-END:variables
}
